### PR TITLE
VISA Raw connections fix

### PR DESCRIPTION
**Pull request by rassouly**
This fixes some bug caused by 2f6d9bdde0afd13edd1df39fff945434b1de8e17 (I think) that caused the profile selection window to crash whenever an instrument with a VISARaw connection was selected.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Could you add a test so that this regression does not reappear ?

**Comment by rassouly** [comment]
I've added a test however when I recreate the bug, instead of failing the test, pytest simply crashes with an INTERNALERROR. This is rather annoying since even catching the exception inside the test doesn't solve the problem.

**Comment by MatthieuDartiailh** [comment]
Indeed this seems a bit harsh. Hopefully we will never break that test. 

Should I merge ?

**Comment by rassouly** [comment]
The error I'm getting is  `AttributeError: 'enaml.dynamicscope.DynamicScope' object has no attribute 'get'`.
I've noticed that I can prevent pytest from crashing by catching the exception and asserting True! It looks ridiculous but is solves the issue and still fails the test because of one variable being used before it's declared when the exception is caught. Should I do that?

**Comment by MatthieuDartiailh** [comment]
Don't bother the next release of enaml add get to the DynamicScope and I hope to get it out in a week or two.

**Comment by rassouly** [comment]
> Don't bother the next release of enaml add get to the DynamicScope and I hope to get it out in a week or two.

Nice! You can merge this then.
